### ISSUE TITLE
Create PhoneDTO

### ISSUE THREAD

**Issue by Legolai** [Legolai/sem3-CA1#11]
### Pre requirements

- #5 

### The tasks

- [x] Create a Java DTO of Phone entity class
- [x] Getters/Setters
- [x] Equal
- [x] toString
- [x] Number
- [x] Description
- [x] Constructor than takes a Phone entity
- [x] toDTOs takes list of Phones

**Comment by DevPJ9** [comment]
Hello @Legolai. I would like to work on it.
