### ISSUE TITLE
Create HobbyDTO

### ISSUE THREAD

**Issue by Legolai** [Legolai/sem3-CA1#12]
### Pre requirements

- #6 

### The Tasks

- [x]  Create a Java DTO of Hobby entity class
- [x] Getters/Setters
- [x] Equal
- [x] toString
- [x] Name
- [x] Description
- [x] Category
- [x] Type
- [x] Members (List of map.entries [first name and lastname]: PersonId)
- [x] Constructor than takes a Hobby entity
- [x] toDTOs takes list of Hobby

**Comment by DevPJ9** [comment]
Hello @Legolai. I would like to work on it.
