### ISSUE TITLE
Create HobbyDTOFacade

### ISSUE THREAD

**Issue by Legolai** [Legolai/sem3-CA1#21]
### Pre requirements

- #6 
- #12 

### The tasks

- [x] Create HobbyDTOFacade
- [x] Get all HobbyDTOs
- [x] Get all Hobbies and the amount of members
- [x] Add Hobby
- [x] Delete Hobby
- [x] Update Hobby

**Comment by DevPJ9** [comment]
Hey @Legolai. I would like to work on this.
